linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - unparam
    - deadcode
    - gosimple
    - structcheck
    - varcheck
    - unused
