name: test tinygo

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  test_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.26.0
      
      - name: Test base58
        run: tinygo test -target=wasm -v ./base58
      - name: Test tezos
        run: tinygo test -target=wasm -v ./tezos